import { type NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";

import HeroSection from "@/components/HomePage/HeroSection";
import TimelineSection from "@/components/HomePage/TimelineSection";
import AboutUsSection from "@/components/HomePage/AboutUsSection";
import OurProjectsSection from "@/components/HomePage/OurProjectsSection";
import OurTools from "@/components/HomePage/OurToolsSection";

interface ICustomProps {
  screenWidth: number;
}

const Home: NextPage<ICustomProps> = (props: ICustomProps) => {
  const [screenWidth, setScreenWidth] = useState(1536);
  useEffect(() => {
    window.addEventListener("resize", () => {
      setScreenWidth(window.innerWidth);
    });
  }, []);

  return (
    <div className="scrollbar-hide">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AboutUsSection />
      <TimelineSection screenWidth={screenWidth} />
      <OurProjectsSection screenWidth={screenWidth} />
      <OurTools />
    </div>
  );
};

export default Home;
